name: My first workflow
on: 
  push:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  job1:
    runs-on : ubuntu-latest
    steps: 
      - name: Get Code from github
        uses: actions/checkout@v6
      - name: run ls
        run: ls -a
